apiVersion: apps/v1
kind: Deployment
metadata:
  name: admission-webhook-cml-user-deployment
  labels:
    app: admission-webhook-cml-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admission-webhook-cml-user
  template:
    metadata:
      labels:
        app: admission-webhook-cml-user
    spec:
      serviceAccount: admission-webhook-cml-user-sa
      containers:
        - name: admission-webhook-cml-user
          image: daocloud.io/daocloud/admission-webhook-cml-user:latest
          imagePullPolicy: Always
          args:
            - -tlsCertFile=/etc/webhook/certs/cert.pem
            - -tlsKeyFile=/etc/webhook/certs/key.pem
            - -alsologtostderr
            - -v=4
            - 2>&1
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: admission-webhook-cml-user-certs
