apiVersion: v1
kind: ServiceAccount
metadata:
  name: admission-webhook-cml-user-sa
  labels:
    app: admission-webhook-cml-user

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: admission-webhook-cml-user-cr
  labels:
    app: admission-webhook-cml-user
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - events
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - pods
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"
- apiGroups:
  - autoscaling
  resources:
  - '*'
  verbs:
  - '*'

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admission-webhook-cml-user-crb
  labels:
    app: admission-webhook-cml-user
subjects:
- kind: ServiceAccount
  name: admission-webhook-cml-user-sa
  namespace: jiexun-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admission-webhook-cml-user-cr
